version: "3.2"
   
services:
  producer:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - '81:81'
    restart: always
    expose:
      - '81'
    networks:
       - red-api
    environment:
      - URL_DATABASE=${URL_DATABASE}
networks:
  red-api:
    external: true