version: "3.2"

services:
  service-api:
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - .:/app
    ports:
      - 80:80
    restart: on-failure
    expose:
      - 80
    networks:
       - red-api
    environment:
      - URL_DATABASE=${URL_DATABASE}
networks:
  red-api:
    external: true