version: "3"

services:
  service-api:
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - .:/app
    ports:
      - 80:80
    extra_hosts:
      - "localhost"
    restart: on-failure