version: "3.2"

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - '6379:6379'
    restart: always
    expose:
      - '6379'
    networks:
       - red-api
       
networks:
  red-api:
    external: true